meta_product_name: "Traxpro"
meta_title: "Traxpro - Oversight for your property assets"
meta_description: "The easiest way to track facilities issues"
meta_image: "construction-5.jpg" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
